Neos:
  Neos:
    fusion:
      autoInclude:
        Sitegeist.Kaleidoscope: true

  Flow:
    mvc:
      routes:
        'Sitegeist.Kaleidoscope':
          position: 'before Neos.Neos'

Sitegeist:
  Kaleidoscope:
    fallbackFormat: 'png'
    overrideImagineDriver: false
